Algoritmo "areaCirculo"
// Disciplina   : [Logica de Programacao]
// Professor   : Jailson
// Descrição   : calcular a area de um circulo
// Autor(a)    : Davi Barbosa
// Data atual  : 03/09/2024
Var
//variaveis
  raio: real
  area: real
Inicio
//codigo
   escreval("Qual o valor do raio do circulo")
   leia(raio)
   area <- pi * (raio * raio)
   escreva("A area do circulo e: ",area:2:2)
Fimalgoritmo