Algoritmo "diasvividos"

Var

ano,mes,dia,resultado: inteiro
Inicio

escreva("Digita a quantidade de anos vividos: ")
leia(ano)
escreva("Digite a quantidade de meses passado do seu ultimo aniversario: ")
leia(mes)
escreva("Digite a quantidade de dias passados do seu ultimo mesversario: ")
leia(dia)

resultado <- ano*365+mes*30+dia

escreva("Quantidades de dias vividos e: ", resultado)
Fimalgoritmo